# Generated by Django 3.2.18 on 2023-03-30 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('hangout', 'Hang out'), ('groupchat', 'Group chat'), ('groomingparty', 'Grooming party'), ('dogbullying', 'Dog bullying'), ('birdwatching', 'Bird watching'), ('newfriends', 'New friends'), ('stupidhumans', 'Stupid humans')], max_length=80)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
