# Generated by Django 3.2.18 on 2023-03-31 15:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hangout', 'Hang out'), ('groupchat', 'Group chat'), ('groomingparty', 'Grooming party'), ('dogbullying', 'Dog bullying'), ('birdwatching', 'Bird watching'), ('newfriends', 'New friends'), ('stupidhumans', 'Stupid humans')], max_length=80),
        ),
    ]
