# Generated by Django 3.2.18 on 2023-04-01 17:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hangout', 'hang out'), ('groupchat', 'group chat'), ('groomingparty', 'grooming party'), ('dogbullying', 'dog bullying'), ('birdwatching', 'bird watching'), ('newfriends', 'new friends'), ('stupidhumans', 'stupid humans')], max_length=80),
        ),
    ]
