# Generated by Django 3.2.18 on 2023-04-17 15:40

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='IE', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../head4_20230408061748_250x250_b9k2w2', upload_to='images/'),
        ),
    ]
