# Generated by Django 3.2.18 on 2023-04-01 17:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20230330_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seeking',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('love', 'love'), ('friends', 'friends'), ('playdates', 'play dates'), ('chatonly', 'chat only'), ('huntingpartner', 'hunting partner')], max_length=46),
        ),
    ]
