# Generated by Django 3.2.18 on 2023-04-15 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='seeking',
        ),
    ]
