# Generated by Django 3.2.18 on 2023-04-17 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=400)),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('grooming', 'grooming'), ('dogbullying', 'dog bullying'), ('birdwatching', 'bird watching'), ('stupidhumans', 'stupid humans'), ('thoughtoftheday', 'thought of the day')], max_length=62)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
