# Generated by Django 3.2.18 on 2023-04-02 18:11

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='personal',
            name='country',
            field=django_countries.fields.CountryField(default='IE', max_length=2),
        ),
    ]
