# Generated by Django 3.2.18 on 2023-04-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0002_auto_20230402_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='connection_made',
        ),
    ]
