# Generated by Django 3.2.18 on 2023-04-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0003_remove_personal_connection_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
